## Deliverable 3. Create a Travel Itinerary Map.

In [22]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

# Importing maps
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")

vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Vaini,TO,82.56,few clouds,-21.2000,-175.2000,Nukuhetulu
1,1,Lapao,BR,69.44,clear sky,-11.3833,-41.8319,Lapão
2,2,Atuona,PF,79.03,light rain,-9.8000,-139.0333,Atuona
3,6,Bowen,AU,82.71,overcast clouds,-20.0167,148.2333,Bowen
4,8,Saint-Philippe,RE,74.21,few clouds,-21.3585,55.7679,Saint-Philippe

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
# Trip to US.
# Get hotels from the results and store the name.
us_vacation_df = vacation_df.loc[(vacation_df["Country"] == "US")]

us_vacation_df.dropna()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
16,29,Kapaa,US,80.58,broken clouds,22.0752,-159.3190,Kapaʻa
20,40,Kahului,US,77.85,clear sky,20.8947,-156.4700,Kahului
29,52,Portland,US,60.82,overcast clouds,45.5234,-122.6762,Portland
45,83,Hilo,US,79.11,clear sky,19.7297,-155.0900,Hilo
47,89,Half Moon Bay,US,65.88,mist,37.4636,-122.4286,Half Moon Bay
48,90,San Patricio,US,71.69,clear sky,28.0170,-97.5169,Sinton
55,107,Laguna,US,78.40,few clouds,38.4210,-121.4238,Sacramento
56,109,Lompoc,US,66.34,mist,34.6391,-120.4579,Lompoc
73,136,Pacific Grove,US,61.56,overcast clouds,36.6177,-121.9166,Monterey
88,159,Lamesa,US,70.52,clear sky,32.7376,-101.9510,Lamesa
91,165,Saint George,US,79.25,clear sky,37.1041,-113.5841,St. George
149,266,Palatka,US,65.98,clear sky,29.6486,-81.6376,Palatka
180,335,Edgewater,US,66.09,few clouds,28.9889,-80.9023,New Smyrna Beach
197,370,Makakilo City,US,77.61,scattered clouds,21.3469,-158.0858,Kapolei
205,384,Ahuimanu,US,82.11,scattered clouds,21.4447,-157.8378,Honolulu
243,460,Houma,US,64.40,clear sky,29.5958,-90.7195,Houma
251,472,Havelock,US,63.95,scattered clouds,34.8791,-76.9013,Havelock
255,480,San Joaquin,US,79.05,clear sky,37.9333,-121.3011,Stockton
277,523,Hays,US,69.35,clear sky,30.0502,-98.0336,Wimberley
312,608,Homestead,US,72.00,few clouds,25.4687,-80.4776,Homestead

In [34]:
# New order for the Data Frame
new_column_order = ["City_ID", "City", "Country", "Lat","Lng", "Max Temp", "Current Description"]

us_vacation_df = us_vacation_df[new_column_order]

us_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
16,29,Kapaa,US,22.0752,-159.3190,80.58,broken clouds
20,40,Kahului,US,20.8947,-156.4700,77.85,clear sky
29,52,Portland,US,45.5234,-122.6762,60.82,overcast clouds
45,83,Hilo,US,19.7297,-155.0900,79.11,clear sky
47,89,Half Moon Bay,US,37.4636,-122.4286,65.88,mist
48,90,San Patricio,US,28.0170,-97.5169,71.69,clear sky
55,107,Laguna,US,38.4210,-121.4238,78.40,few clouds
56,109,Lompoc,US,34.6391,-120.4579,66.34,mist
73,136,Pacific Grove,US,36.6177,-121.9166,61.56,overcast clouds
88,159,Lamesa,US,32.7376,-101.9510,70.52,clear sky
91,165,Saint George,US,37.1041,-113.5841,79.25,clear sky
149,266,Palatka,US,29.6486,-81.6376,65.98,clear sky
180,335,Edgewater,US,28.9889,-80.9023,66.09,few clouds
197,370,Makakilo City,US,21.3469,-158.0858,77.61,scattered clouds
205,384,Ahuimanu,US,21.4447,-157.8378,82.11,scattered clouds
243,460,Houma,US,29.5958,-90.7195,64.40,clear sky
251,472,Havelock,US,34.8791,-76.9013,63.95,scattered clouds
255,480,San Joaquin,US,37.9333,-121.3011,79.05,clear sky
277,523,Hays,US,30.0502,-98.0336,69.35,clear sky
312,608,Homestead,US,25.4687,-80.4776,72.00,few clouds

In [47]:
# Asking the user for the cities for the trip, from the previous Data Frame

start = float(input("Where would you like your trip to start Starting City_ID?    "))
stop1 = float(input("Where would you like your 1st Stop to be in City_ID?         "))
stop2 = float(input("Where would you like your 2nd Stop to be in City_ID?         "))
stop3 = float(input("Where would you like your 3rd Stop to be in City_ID?         "))
end = float(input("Where would you like your trip to end in City_ID?            "))

Where would you like your trip to start Starting City_ID?    523
Where would you like your 1st Stop to be in City_ID?         608
Where would you like your 2nd Stop to be in City_ID?         480
Where would you like your 3rd Stop to be in City_ID?         335
Where would you like your trip to end in City_ID?            165

In [ ]:
# Asking the user for the cities for the trip, from the previous Data Frame

#start = str(input("Where would you like your trip to start Starting City?    "))
#stop1 = str(input("Where would you like your 1st Stop to be in City?    "))
#stop2 = str(input("Where would you like your 2nd Stop to be in City?    "))
#stop3 = str(input("Where would you like your 3rd Stop to be in City?    "))
#end = str(input("Where would you like your trip to end in City? "    ))

In [49]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

# Start Vacation at:

vacation_start = us_vacation_df.loc[(us_vacation_df["City_ID"] == start)]
vacation_start = vacation_start.iloc[0]

vacation_stop_1 = us_vacation_df.loc[(us_vacation_df["City_ID"] == stop1)]
vacation_stop_1 = vacation_stop_1.iloc[0]

vacation_stop_2 = us_vacation_df.loc[(us_vacation_df["City_ID"] == stop2)]
vacation_stop_2 = vacation_stop_2.iloc[0]

vacation_stop_3 = us_vacation_df.loc[(us_vacation_df["City_ID"] == stop3)]
vacation_stop_3 = vacation_stop_3.iloc[0]

vacation_end = us_vacation_df.loc[(us_vacation_df["City_ID"] == end)]
vacation_end = vacation_end.iloc[0]
                                     
print("Your Starting Destination is " + vacation_start["City"] + ", " + vacation_start["Country"])
print("Your First Stop is " + vacation_stop_1["City"] + ", " + vacation_stop_1["Country"])
print("Your Second Stop is " + vacation_stop_2["City"] + ", " + vacation_stop_2["Country"])                                     
print("Your Thirth Stop is " + vacation_stop_3["City"] + ", " + vacation_stop_3["Country"])                                     
print("Your Last Stop in your vacation is " + vacation_end["City"] + ", " + vacation_end["Country"])

Your Starting Destination is Hays, US
Your First Stop is Homestead, US
Your Second Stop is San Joaquin, US
Your Thirth Stop is Edgewater, US
Your Last Stop in your vacation is Saint George, US

In [50]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]]
print("Your Starting City Lat and Long")
print(start) 

stop1 = vacation_stop_1[["Lat", "Lng"]]
print("Your 1st Stop City Lat and Long")
print(stop1) 

stop2 = vacation_stop_2[["Lat", "Lng"]]
print("Your 2nd Stop City Lat and Long")
print(stop2) 

stop3 = vacation_stop_3[["Lat", "Lng"]]
print("Your 3rd Stop City Lat and Long")
print(stop3) 

end = vacation_end[["Lat", "Lng"]]
print("Your end City Lat and Long")
print(end)

Your Starting City Lat and Long
Lat    30.0502
Lng   -98.0336
Name: 277, dtype: object
Your 1st Stop City Lat and Long
Lat    25.4687
Lng   -80.4776
Name: 312, dtype: object
Your 2nd Stop City Lat and Long
Lat     37.9333
Lng   -121.3011
Name: 255, dtype: object
Your 3rd Stop City Lat and Long
Lat    28.9889
Lng   -80.9023
Name: 180, dtype: object
Your end City Lat and Long
Lat     37.1041
Lng   -113.5841
Name: 91, dtype: object

In [51]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

# Using Driving moder since long distances
start = (30.0502,-98.0336)
stop1 = (25.4687,-80.4476)
stop2 = (37.9333,-121.3011)
stop3 = (28.9889,-80.9023)
end = (37.1041,-113.5841)

fig = gmaps.figure()
sart2end_via_stops = gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(sart2end_via_stops)
fig

Figure(layout=FigureLayout(height='420px'))

In [52]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.

us_vacation_df = pd.concat([us_vacation_df],ignore_index=True)
us_vacation_df

,City_ID,City,Country,Lat,Lng,Max Temp,Current Description
0,29,Kapaa,US,22.0752,-159.3190,80.58,broken clouds
1,40,Kahului,US,20.8947,-156.4700,77.85,clear sky
2,52,Portland,US,45.5234,-122.6762,60.82,overcast clouds
3,83,Hilo,US,19.7297,-155.0900,79.11,clear sky
4,89,Half Moon Bay,US,37.4636,-122.4286,65.88,mist
5,90,San Patricio,US,28.0170,-97.5169,71.69,clear sky
6,107,Laguna,US,38.4210,-121.4238,78.40,few clouds
7,109,Lompoc,US,34.6391,-120.4579,66.34,mist
8,136,Pacific Grove,US,36.6177,-121.9166,61.56,overcast clouds
9,159,Lamesa,US,32.7376,-101.9510,70.52,clear sky
10,165,Saint George,US,37.1041,-113.5841,79.25,clear sky
11,266,Palatka,US,29.6486,-81.6376,65.98,clear sky
12,335,Edgewater,US,28.9889,-80.9023,66.09,few clouds
13,370,Makakilo City,US,21.3469,-158.0858,77.61,scattered clouds
14,384,Ahuimanu,US,21.4447,-157.8378,82.11,scattered clouds
15,460,Houma,US,29.5958,-90.7195,64.40,clear sky
16,472,Havelock,US,34.8791,-76.9013,63.95,scattered clouds
17,480,San Joaquin,US,37.9333,-121.3011,79.05,clear sky
18,523,Hays,US,30.0502,-98.0336,69.35,clear sky
19,608,Homestead,US,25.4687,-80.4776,72.00,few clouds

In [53]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
mark_info = [info_box_template.format(**row) for index, row in us_vacation_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = us_vacation_df[["Lat", "Lng"]]

In [55]:
# 11a. Add a marker layer for each city to the map.
city_mark = us_vacation_df["City"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=mark_info)

fig.add_layer(marker_layer)

In [56]:
# Display Map
fig

Figure(layout=FigureLayout(height='420px'))